# Merge 3 Years of Electricity Data

In [1]:
import sys
import os
# Get the parent directory
parent_folder = os.path.dirname(os.getcwd())
# add the parent directory to the Python path so that the scripts can be imported
sys.path.append(parent_folder)

In [2]:
# Import libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import pvlib
from modules.utils import read_column_list_from_config

In [3]:
fname_2010_2011 = '../data/ausgrid/ausgrid_2010_2011.csv'
fname_2011_2012 = '../data/ausgrid/ausgrid_2011_2012.csv'
fname_2012_2013 = '../data/ausgrid/ausgrid_2012_2013.csv'
df_2010_2011 = pd.read_csv(
    fname_2010_2011, index_col=0, parse_dates=['datetime'])
df_2011_2012 = pd.read_csv(
    fname_2011_2012, index_col=0, parse_dates=['datetime'])
df_2012_2013 = pd.read_csv(
    fname_2012_2013, index_col=0, parse_dates=['datetime'])

## Merge the dataframes

In [4]:
df_merged = pd.concat([df_2010_2011, df_2011_2012, df_2012_2013])
# The result has all columns from both dataframes (union of columns)
# Missing columns are filled with NaN values

In [5]:
# print the shape of the dataframes
print(df_2010_2011.shape)
print(df_2011_2012.shape)
print(df_2012_2013.shape)
# print the shape of the merged dataframe
print(df_merged.shape)

(17520, 906)
(17568, 906)
(17520, 903)
(52608, 906)

In [6]:
df_2010_2011.head()

,datetime,HoD,dow,doy,month,year,1_pv,1_con,1_net,2_pv,...,297_net,298_pv,298_con,298_net,299_pv,299_con,299_net,300_pv,300_con,300_net
0,2010-07-01 00:00:00,0,3,182,7,2010,0.0,606.0,606.0,0.0,...,410.0,0.0,192.0,192.0,0.0,2928.0,2928.0,0.0,558.0,558.0
1,2010-07-01 00:30:00,0,3,182,7,2010,0.0,942.0,942.0,0.0,...,212.0,0.0,220.0,220.0,0.0,2826.0,2826.0,0.0,1848.0,1848.0
2,2010-07-01 01:00:00,1,3,182,7,2010,0.0,166.0,166.0,0.0,...,338.0,0.0,160.0,160.0,0.0,2856.0,2856.0,0.0,1606.0,1606.0
3,2010-07-01 01:30:00,1,3,182,7,2010,0.0,242.0,242.0,0.0,...,540.0,0.0,210.0,210.0,0.0,2890.0,2890.0,0.0,132.0,132.0
4,2010-07-01 02:00:00,2,3,182,7,2010,0.0,722.0,722.0,0.0,...,510.0,0.0,178.0,178.0,0.0,2814.0,2814.0,0.0,178.0,178.0

In [7]:
df_merged.head()

,datetime,HoD,dow,doy,month,year,1_pv,1_con,1_net,2_pv,...,297_net,298_pv,298_con,298_net,299_pv,299_con,299_net,300_pv,300_con,300_net
0,2010-07-01 00:00:00,0,3,182,7,2010,0.0,606.0,606.0,0.0,...,410.0,0.0,192.0,192.0,0.0,2928.0,2928.0,0.0,558.0,558.0
1,2010-07-01 00:30:00,0,3,182,7,2010,0.0,942.0,942.0,0.0,...,212.0,0.0,220.0,220.0,0.0,2826.0,2826.0,0.0,1848.0,1848.0
2,2010-07-01 01:00:00,1,3,182,7,2010,0.0,166.0,166.0,0.0,...,338.0,0.0,160.0,160.0,0.0,2856.0,2856.0,0.0,1606.0,1606.0
3,2010-07-01 01:30:00,1,3,182,7,2010,0.0,242.0,242.0,0.0,...,540.0,0.0,210.0,210.0,0.0,2890.0,2890.0,0.0,132.0,132.0
4,2010-07-01 02:00:00,2,3,182,7,2010,0.0,722.0,722.0,0.0,...,510.0,0.0,178.0,178.0,0.0,2814.0,2814.0,0.0,178.0,178.0

## Keep only cluster 5 data
Keep only the cluster 5 data.

In [8]:
# list_cluster_5 = [22, 24, 25, 26, 33, 35, 41, 47, 51, 52, 59, 73, 77, 87, 88, 93, 103, 107, 108, 110, 111, 119, 122, 124, 125, 133, 138, 144,
#                   148, 151, 153, 157, 163, 170, 175, 188, 200, 201, 203, 207, 211, 214, 222, 230, 231, 240, 252, 253, 256, 259, 261, 263, 269, 281, 285, 290]
list_cluster_5 = read_column_list_from_config(
    '../config/cluster5_customers.txt')

# Create all cluster 5 columns in one line
cluster_5_columns = [
    f"{id}_{suffix}" for id in list_cluster_5 for suffix in ['pv', 'con', 'net']]
columns_to_keep = ['datetime', 'HoD', 'dow',
                   'doy', 'month', 'year'] + cluster_5_columns

# Filter the dataframe
df_merged_cluster_5 = df_merged[columns_to_keep]

print(f"Original df_merged shape: {df_merged.shape}")
print(f"Filtered df_merged_cluster_5 shape: {df_merged_cluster_5.shape}")
# Show first 10 columns

Original df_merged shape: (52608, 906)
Filtered df_merged_cluster_5 shape: (52608, 237)

In [9]:
df_merged_cluster_5.columns

Index(['datetime', 'HoD', 'dow', 'doy', 'month', 'year', '4_pv', '4_con',
       '4_net', '6_pv',
       ...
       '282_net', '288_pv', '288_con', '288_net', '291_pv', '291_con',
       '291_net', '298_pv', '298_con', '298_net'],
      dtype='object', length=237)

## Find the difference of columns between the three dataframes

In [10]:
# find the difference of columns between the three dataframes

# Get column names for each dataframe
cols_2010_2011 = set(df_2010_2011.columns)
cols_2011_2012 = set(df_2011_2012.columns)
cols_2012_2013 = set(df_2012_2013.columns)

print("Column counts:")
print(f"2010-2011: {len(cols_2010_2011)} columns")
print(f"2011-2012: {len(cols_2011_2012)} columns")
print(f"2012-2013: {len(cols_2012_2013)} columns")
print()

# Find columns that are in 2010-2011 but not in others
only_in_2010_2011 = cols_2010_2011 - cols_2011_2012 - cols_2012_2013
print(f"Columns only in 2010-2011: {len(only_in_2010_2011)}")
if only_in_2010_2011:
    print(sorted(only_in_2010_2011))
print()

# Find columns that are in 2011-2012 but not in others
only_in_2011_2012 = cols_2011_2012 - cols_2010_2011 - cols_2012_2013
print(f"Columns only in 2011-2012: {len(only_in_2011_2012)}")
if only_in_2011_2012:
    print(sorted(only_in_2011_2012))
print()

# Find columns that are in 2012-2013 but not in others
only_in_2012_2013 = cols_2012_2013 - cols_2010_2011 - cols_2011_2012
print(f"Columns only in 2012-2013: {len(only_in_2012_2013)}")
if only_in_2012_2013:
    print(sorted(only_in_2012_2013))
print()

# Find common columns across all three dataframes
common_cols = cols_2010_2011 & cols_2011_2012 & cols_2012_2013
print(f"Common columns across all three: {len(common_cols)}")
print()

# Find columns that are missing in 2012-2013 compared to others
missing_in_2012_2013 = (cols_2010_2011 | cols_2011_2012) - cols_2012_2013
print(f"Columns missing in 2012-2013: {len(missing_in_2012_2013)}")
if missing_in_2012_2013:
    print(sorted(missing_in_2012_2013))

Column counts:
2010-2011: 906 columns
2011-2012: 906 columns
2012-2013: 903 columns

Columns only in 2010-2011: 0

Columns only in 2011-2012: 0

Columns only in 2012-2013: 0

Common columns across all three: 903

Columns missing in 2012-2013: 3
['2_con', '2_net', '2_pv']

In [11]:
# Examine the column structure to understand how household IDs are represented
print("First 20 columns:")
print(df_merged.columns[:20].tolist())
print("\nLast 20 columns:")
print(df_merged.columns[-20:].tolist())
print(f"\nTotal columns: {len(df_merged.columns)}")
print(f"Total rows: {len(df_merged)}")

First 20 columns:
['datetime', 'HoD', 'dow', 'doy', 'month', 'year', '1_pv', '1_con', '1_net', '2_pv', '2_con', '2_net', '3_pv', '3_con', '3_net', '4_pv', '4_con', '4_net', '5_pv', '5_con']

Last 20 columns:
['294_con', '294_net', '295_pv', '295_con', '295_net', '296_pv', '296_con', '296_net', '297_pv', '297_con', '297_net', '298_pv', '298_con', '298_net', '299_pv', '299_con', '299_net', '300_pv', '300_con', '300_net']

Total columns: 906
Total rows: 52608

In [12]:
# Check if household IDs are in the column names
# Look for columns that might contain household IDs
household_columns = [col for col in df_merged.columns if col.isdigit()]
print(
    f"Columns that are purely numeric (potential household IDs): {len(household_columns)}")
print("First 10 numeric columns:", household_columns[:10])
print("Last 10 numeric columns:", household_columns[-10:])

# Check if any of the cluster 5 IDs are in the columns
cluster_5_in_columns = [
    str(id) for id in list_cluster_5 if str(id) in df_merged.columns]
print(f"\nCluster 5 IDs found in columns: {len(cluster_5_in_columns)}")
print("Cluster 5 IDs in columns:", cluster_5_in_columns[:10])

Columns that are purely numeric (potential household IDs): 0
First 10 numeric columns: []
Last 10 numeric columns: []

Cluster 5 IDs found in columns: 0
Cluster 5 IDs in columns: []

## Save the merged dataframe

In [13]:
df_merged_cluster_5.to_csv('../data/ausgrid/ausgrid_3_years.csv', index=False)

In [14]:
df_merged_cluster_5.columns

Index(['datetime', 'HoD', 'dow', 'doy', 'month', 'year', '4_pv', '4_con',
       '4_net', '6_pv',
       ...
       '282_net', '288_pv', '288_con', '288_net', '291_pv', '291_con',
       '291_net', '298_pv', '298_con', '298_net'],
      dtype='object', length=237)